In [0]:
class classnames:
  #Some function and varaibles 
  #Function --- used to perform the specific activity
  #Variables--- data("memory")

In [0]:
def test():
  return
test()


In [0]:
class demo:
  def test():
    print("test() for the class and medhod")
    return
  
obj=demo()
obj=test()

In [0]:
class demo:
  def fact(self,n):
    #$return the factorial
    fact=1
    while(n!=0):
      fact=fact*n
      n=n-1
    return fact

p1=demo()
print(p1.fact(5))#120

120


In [0]:
class demo2:
  def accept(self,p1,p2):
    self.p1=p1
    self.p2=p2
    return
  def display(self):
    print("p1=",p1)
    print("p2=",p2)
    
c1=demo2()
c1.accept(10,20)
c1.display()
  

p1= <__main__.demo object at 0x7fc4dc98f5c0>


NameError: ignored

In [0]:
class demo2:
  def __init__(self,p1,p2):
    self.p1=p1
    self.p2=p2
  def add(self,p1,p2):
    return p1+p2
  
c1=demo2(10,20)
print(c1.add(100,200))
  

300


In [0]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
a1=np.array(1,2,3),(4,5,6)
print("S")

In [0]:
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

14

In [0]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [0]:
b1=np.array([(1,5),(6,9)])
b2=np.array([(1,3),(1,6)])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])

###Pandas Basics

In [0]:
import pandas as pd 
dict={"Name":["Anil","Akhil","Dinesh","Harsha","Ajay","Kran"],"EmailID":["anil@hmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","Kran@gmail.com"],"Mobile number":[999,888,777,888,777,999],"Address":["Hyd","Hyd","Hyd","Hyd","Hyd","Hyd"]}
b=pd.DataFrame(dict)
print(b)

     Name           EmailID  Mobile number Address
0    Anil    anil@hmail.com            999     Hyd
1   Akhil   akhil@gmail.com            888     Hyd
2  Dinesh  dinesh@gmail.com            777     Hyd
3  Harsha  harsha@gmail.com            888     Hyd
4    Ajay    ajay@gmail.com            777     Hyd
5    Kran    Kran@gmail.com            999     Hyd


In [0]:
b.index=["01","02","03","04","05","06"]
print(b)

      Name           EmailID  Mobile number Address
01    Anil    anil@hmail.com            999     Hyd
02   Akhil   akhil@gmail.com            888     Hyd
03  Dinesh  dinesh@gmail.com            777     Hyd
04  Harsha  harsha@gmail.com            888     Hyd
05    Ajay    ajay@gmail.com            777     Hyd
06    Kran    Kran@gmail.com            999     Hyd
